import RealtimeVFX from "@/components/layout/RealtimeVFX";

import { Geist, Geist_Mono, Inter, Montserrat, Poppins } from "next/font/google";
import "./globals.css";
;



const geistSans = Geist( {
  variable: "--font-geist-sans",
  subsets: ["latin"],
} );

const geistMono = Geist_Mono( {
  variable: "--font-geist-mono",
  subsets: ["latin"],
} );

const montserrat = Montserrat( {
  subsets: ["latin"]
} );

const poppins = Poppins( {
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
} );

const inter = Inter( {
  subsets: ["latin"]
} );

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout( { children } ) {
  return (
    <html lang="en">
      <body
        className={` ${inter.className} antialiased`}
      >
        <RealtimeVFX>
          {/* <ScrollContainer> */}


          {children}

          {/* </ScrollContainer> */}
        </RealtimeVFX>
      </body>
    </html>
  );
}
